server:
  port: 8882
spring:
  application:
    name: config-client
  rabbitmq:
    host: 192.168.1.56
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/