server:
  port: 8888
spring:
  application:
    name: gateway-service
  profiles:
    active: limit-route
  redis:
    host: 192.168.1.54
    password: 123456
    port: 6379
    database: 0
---
spring:
  cloud:
    gateway:
      routes:
        - id: limit-route
          uri: http://httpbin.org:80/get
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
  profiles: limit-route
---
# curl localhost:8888
spring:
  cloud:
    gateway:
      routes:
        - id: time-route
          uri: http://httpbin.org:80
          filters:
            - RequestTime=false
          predicates:
            # \u5728\u67D0\u4E2A\u65F6\u95F4\u524D\u624D\u4F1A\u88AB\u8F6C\u53D1
            - Before=2019-11-09T08:10:10.789-07:00[America/Denver]
            # \u5728\u67D0\u4E2A\u65F6\u95F4\u540E\u624D\u4F1A\u88AB\u8F6C\u53D1
            # - After=2019-11-06T10:10:10.789-07:00[America/Denver]
            # \u5728\u67D0\u4E2A\u65F6\u95F4\u6BB5\u5185\u624D\u4F1A\u88AB\u8F6C\u53D1
            # - Between=2019-11-06T10:10:10.789-07:00[America/Denver], 2020-01-01T10:10:10.789-07:00[America/Denver]
  profiles: time-route
---
# curl -H 'X-Request-Id:1' localhost:8888
spring:
  cloud:
    gateway:
      routes:
        - id: header-route
          uri: http://httpbin.org:80
          predicates:
            - Header=X-Request-Id, \d+
  profiles: header-route
---
# curl -H 'Cookie:name=lilei' localhost:8888
spring:
  cloud:
    gateway:
      routes:
        - id: cookie-route
          uri: http://httpbin.org:80
          predicates:
            - Cookie=name, lilei
  profiles: cookie-route
---
# curl -H 'Host:runrm.com' localhost:8888
spring:
  cloud:
    gateway:
      routes:
        - id: host-route
          uri: http://httpbin.org:80
          predicates:
            - Host=**.runrm.com
  profiles: host-route
---
# curl localhost:8888
# curl -XPOST localhost:8888\u7ED3\u679C\u4E3A404
spring:
  cloud:
    gateway:
      routes:
        - id: method-route
          uri: http://httpbin.org:80
          predicates:
            - Method=GET
  profiles: method-route
---
# curl localhost:8888/test/setlilei
spring:
  cloud:
    gateway:
      routes:
        - id: path-route
          uri: http://httpbin.org:80
          predicates:
            - Path=/get/**
          filters:
            - RewritePath=/get/(?<segment>.*), /$\{segment}
  profiles: path-route
---
# curl localhost:8888?name=lilei
spring:
  cloud:
    gateway:
      routes:
        - id: query-route
          uri: http://httpbin.org:80
          predicates:
            # - Query=name
            - Query=name, li.
          filters:
            # \u8FC7\u6EE4\u5668\u5DE5\u5382\u4F1A\u5728\u8BF7\u6C42\u52A0\u4E0A\u4E00\u5BF9\u8BF7\u6C42\u5934 \u540D\u79F0\u4E3AX-Request-Li\u503C\u4E3ALei
            - AddRequestHeader=X-Request-Li, Lei
  profiles: query-route