server:
#  port: 9411
  compression:
    # \u662F\u5426\u5F00\u542F\u538B\u7F29 \u9ED8\u8BA4false
    enabled: true
spring:
  application:
    name: zipkin-server
  main:
    # \u8BA9\u5E94\u7528\u4EE5\u975Eweb\u670D\u52A1\u65B9\u5F0F\u542F\u52A8 server.port\u914D\u7F6E\u5C06\u4F1A\u5931\u6548
    web-application-type: none